# Generated by Django 3.1.3 on 2021-01-29 10:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image.jpg', max_length=255),
        ),
    ]
