# Generated by Django 3.1.3 on 2021-01-29 13:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='image.jpg', max_length=255)),
                ('amount', models.IntegerField()),
                ('stage', models.CharField(choices=[('Discovery', 'Discovery'), ('Proposal Shared', 'Proposal Shared'), ('Negotiations', 'Negotiations')], max_length=30)),
            ],
        ),
    ]
