# Generated by Django 3.1.3 on 2021-01-29 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='Oname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
