# Generated by Django 3.1.3 on 2021-01-30 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210129_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='Oname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
